### ISSUE TITLE
OOME when group matches empty string

### ISSUE THREAD

**Issue by mschaefers** [tony19/named-regexp#16]
The following code snippet leads to an endless loop in `matcher.namedGroups()` and eventually to an OutOfMemoryError:
```
com.google.code.regexp.Matcher matcher = com.google.code.regexp.Pattern.compile("(?<foo>.*)").matcher("bar");
System.out.println(matcher.namedGroups());
```
Tested with v0.2.6

I would expect that
1. the expression `(?<foo>.*)` matched the whole String `bar` once, because `.*` is greedy (as opposed to `.*?`)
2. no endless loop / OOME occurs, for _any_ given pattern

**Comment by tony19** [comment]
Fixed in https://github.com/tony19/named-regexp/releases/tag/named-regexp-0.2.7
