### ISSUE TITLE
Escaped characters get "un-escaped" when using Matcher.appendReplacement

### ISSUE THREAD

**Issue by vprcic** [tony19/named-regexp#18]
I don't know whether this is still maintained, but there's a bug when using the Matcher.appendReplacement that removes escaping of characters like "\s". Here's a code example:

```
Pattern pattern = Pattern.compile("[0-9]");
Matcher matcher = pattern.matcher("12345");
StringBuffer buffer = new StringBuffer();
while (matcher.find()) {
    matcher.appendReplacement(buffer, matcher.group() + "\\s");
}
matcher.appendTail(buffer);
System.out.println(buffer);
```

This should print "1\s2\s3\s4\s5\s" but prints "1s2s3s4s5s".

**Comment by tony19** [comment]
Thanks for the report. I'll take a look as soon as I can.

**Comment by vprcic** [comment]
Thank you very much!

**Comment by vprcic** [comment]
After some investigation, this seems to also be a problem with regular Matcher class and is resolved using the Matcher.quoteReplacement method. Here's the fixed code example from above:

```
Pattern pattern = Pattern.compile("[0-9]");
Matcher matcher = pattern.matcher("12345");
StringBuffer buffer = new StringBuffer();
while (matcher.find()) {
    matcher.appendReplacement(buffer, Matcher.quoteReplacement(matcher.group() + "\\s"));
}
matcher.appendTail(buffer);
System.out.println(buffer);
```

This prints "1\s2\s3\s4\s5\s" as expected. So, maybe to resolve this issue, all that is needed is to expose the static Matcher.quoteReplacement method in the Matcher class?

**Comment by tony19** [comment]
`Matcher.quoteReplacement` released in https://github.com/tony19/named-regexp/releases/tag/named-regexp-0.2.7
