### ISSUE TITLE
Matcher#namedGroups() returns only first matching subsequence

### ISSUE THREAD

**Issue by wasiek** [tony19/named-regexp#7]
given:

        Pattern pattern = Pattern.compile("(?<digit>\\d)(\\w)");
        Matcher matcher = pattern.matcher("2foo3bar4");

when 

        matcher.namedGroups();

then 
        Only the first group is being found due to reseting of matcher.

**Comment by tony19** [comment]
Thanks for the report.

To me, the main issue is that the return type of `namedGroups()` can only hold one value per group.  Even if the function looped through to collect matches, it would only hold the last value.

I think the fix would require changing the return type to support multiple values per group (e.g., `Map<String, Array<String>>`).

**Comment by wasiek** [comment]
Actually in my case named groups hold information about one object so i need something like List<Map<String, String>>. I've already made a method returning List of Maps but couln't make a pull request.

**Comment by tony19** [comment]
I'm not sure I follow. I assume your list entry would be a map of group name to group value, which seems inefficient compared to a map of group name to multiple group values. Can you clarify how your solution is better?

**Comment by wasiek** [comment]
This is a small example for something that i need.

    Pattern pattern = Pattern.compile("(?<dayOfYear>\\d+).(?<dayName>\\w+)");
    Matcher matcher = pattern.matcher("1 Sunday foo bar 2 Monday foo bar 3 Tuesday foo bar 4 Wednesday foo bar 5 Thursday foo bar 6 Friday foo bar  7 Saturday foo bar 8 Sunday foo bar 9 Monday foo bar 10 Tuesday foo bar ");

In my pattern dayOfYear has to go in pair with dayName. What i want to get is:

    [
        {"dayOfYear": "1", "dayName": "Sunday"},
        {"dayOfYear": "2", "dayName": "Monday"},
        ...
    ]

**Comment by tony19** [comment]
Ok, I see. Try the updated PR.

**Comment by tony19** [comment]
The fix is released in [0.2.5](https://github.com/tony19/named-regexp/releases/tag/named-regexp-0.2.5).
