### ISSUE TITLE
Runs out of memory, when no group is present in the regex

### ISSUE THREAD

**Issue by TamasBarta** [tony19/named-regexp#9]
`Matcher.namedGroups()` is faulty, because when I have no groups in my pattern, the `while` loop never quits, and causes out of memory exception.

Details: `nextIndex` is only updated in the `for`, but when `parentPattern.groupNames()` is empty, it never enters it.

My use case is to use your lib with dynamic regexes (I'm writing a regex capable router, that can extract parameters from URLs, so they may or may not contain groups), so I cannot determine without your lib if they have groups or not, so I cannot use the built-in regex, if I don't have groups.

**Edit**: I just discovered `groupCount()`, but still it would be nice if it wouldn't be needed.

**Comment by tony19** [comment]
@TamasBarta I cannot reproduce. What's the pattern and input you are trying?

**Comment by TamasBarta** [comment]
Cool! Thanks!

**Comment by tony19** [comment]
Fix released in [0.2.6](https://github.com/tony19/named-regexp/releases/tag/named-regexp-0.2.6)

**Comment by TamasBarta** [comment]
Lovely!
